Backend ifc
JJHPhoto/progressing pull request #100
Opened 2021-03-28 07:50 UTC by Ianaac27

2021-03-28 23:43 UTC, Tskading commented
Ian is asking that we do not merge this PR to the main.  It will cause conflicts.  His new push will be the one we want to merge.

2021-03-28 23:56 UTC, Tskading requested changes
NOT MERGING THIS PR; BY IANS REQUEST

2021-03-29 00:01 UTC, Ianaac27 commented
Closing this

2021-03-29 00:08 UTC, Tskading approved these changes

2021-03-29 00:08 UTC, merged